name: Sysinfo Lasttest Build
on:
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 20
    runs-on: [self-hosted, vm-1]
    steps:
      - uses: actions/checkout@v4

      - name: Systeminfo
        run: |
          uname -a
          nproc
          free -h
          df -h

      - name: Fake-Lasttest
        run: |
          echo "CPU burn ðŸ”¥"
          yes > /dev/null &
          PID=$!
          sleep 10
          kill $PID
