name: Test Build

# Starte den Build manuell
on:
  workflow_dispatch:

jobs:
  build:
    # LÃ¤uft nur auf deinem self-hosted Runner
    runs-on: [self-hosted, vm-1]

    steps:
      # Code aus dem Repo auschecken
      - uses: actions/checkout@v3

      # Einfacher Test-Befehl
      - name: Hello World
        run: |
          echo "DedicatedCI Runner funktioniert!"
          uname -a
          lscpu
